### ISSUE TITLE
plansys_bt_example params not loaded correctly on Humble

### ISSUE THREAD

**Issue by stinkyElias** [PlanSys2/ros2_planning_system_examples#45]
Hello

Continuing on #42, a new issue arises. Running the plansys_bt_example with `humble` generates the error

```shell
[bt_action_node-2] [INFO] [1708703917.310511893] [move_1_bb_node]: "move" BtActionNode initialized
[bt_action_node-2] [ERROR] [1708703917.311049000] [move_1]: Caught exception in callback for transition 13
[bt_action_node-2] [ERROR] [1708703917.311068135] [move_1]: Original error: Statically typed parameter 'waypoints' must be initialized.
[bt_action_node-2] [WARN] [1708703917.311079767] [move_1]: Error occurred while doing error handling.
``` 
I can't seem to find the issue. However, checking the `waypoints` parameter that is supposed to be loaded from `params.yaml`, I see that it's not loaded. From `params.yaml`

```
move_1:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["wheels_zone", "steering_wheels_zone", "body_car_zone", "assembly_zone", "recharge_zone"]
    waypoint_coords:
      wheels_zone: [0.0, -2.0, 0.0]
      steering_wheels_zone: [1.8, 0.0, 0.0]
      body_car_zone: [0.0, 2.0, 0.0]
      assembly_zone: [-2.0, -0.4, 0.0]
      recharge_zone: [-2.0, -0.4, 0.0]
``` 

Using `ros2 param list /move_1` returns

```shell
  action_name
  bt_file_logging
  bt_minitrace_logging
  bt_xml_file
  enable_groot_monitoring
  max_msgs_per_second
  plugins
  publisher_port
  rate
  server_port
  specialized_arguments
  use_sim_time
``` 
 and shows that `plugins` for example is loaded correcly
 
 
```shell
$ ros2 param get /move_1 plugins
String values are: ['plansys2_move_bt_node']
``` 

however `waypoints` and `waypoint_coords`is not. I find it weird that some parameters are loaded and some are not. Given that `move_1`don't have `waypoints` it makes sense to me that I receive the aforemention error message. However, I don't understand how to fix this.

As a test, I have verified that all the other examples work as they should, in case it was a setup issue.

I also checked #33 and verified that I have the correct code line.

Have anyone else experienced this?

Thank you

EDIT: The example works fine with `rolling` but not with `humble`
